<?php

namespace Test\Database\Ui\Component\Listing\Column;

use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class MemberActions extends  Column
{
    protected  $url;
    public function __construct(ContextInterface $context,
                                UiComponentFactory $uiComponentFactory,
                                UrlInterface $url,
                                array $components = [],
                                array $data = []
    )
    {
        $this->url = $url;
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    public function prepareDataSource(array $dataSource)
    {
        if(isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as &$item){
                //edit url
                $item[$this->getData('name')]['edit'] = ['href' =>
                    $this->url->getUrl('page/member/edit', ['id' => $item['entity_id']]),
                    'label' => _('Edit'),
                    'hidden' => false
                ];

                //delete url
                $item[$this->getData('name')]['delete'] = ['href' =>
                    $this->url->getUrl('page/member/delete', ['id' => $item['entity_id']]),
                    'label' => _('Delete'),
                    'hidden' => false
                ];
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}
