<?php
namespace Mastering\SampleModule\Ui\Component\Listing\Columns;

use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class SampleActions extends  Column {

    const EDIT_PAGE_URL_PATH= "mastering/item/edit";
    const DELETE_PAGE_URL_PATH= "mastering/item/delete";

    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        UrlInterface $urlBuilder,
        array $components = [],
        array $data = []
    ) {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->urlBuilder = $urlBuilder;

    }

    public function prepareDataSource(array $dataSource)
    {
//        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub

        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                if($item['id']){
                    $item[$this->getData('name')] =[
                        'edit' => [
                            'href' => $this->urlBuilder->getUrl(
                                self::EDIT_PAGE_URL_PATH,
                                [
                                    'id' => $item['id'],
                                ]
                            ),
                            'label' => __('Edit'),
                        ],
                        'delete' => [
                            'href' => $this->urlBuilder->getUrl(
                                self::DELETE_PAGE_URL_PATH,
                                [
                                    'id' => $item['id'],
                                ]
                            ),
                            'label' => __('Delete'),
                            'confirm' => [
                                'title' => __('Delete %1', $item['name']),
                                'message' => __('Are you sure you want to delete a %1 record?', $item['name']),
                            ],
                            'post' => true,
                        ],
                    ];
                        /*
                        [
                        'edit' => [
                            'href' => $this->urlBuilder->getUrl(self::EDIT_PAGE_URL_PATH,
                                [
                                    'id' => $item['id'],
                                ]
                            ),
                            'label' => __('Edit')
                            ]
                        ];
                        */
                }

            }
            }
            return $dataSource;
    }
}
